"""
These declarations describe "gmr.contract.v10". That string is what a caller
pins to know which shapes they may match on; tools/gate.py fails the build
when this file and the runtime disagree about it.

Values cross as plain dicts/lists shaped exactly like the JSON the node
binding serves — dist/npm/index.d.ts is the field-level reference; this stub
carries the callable surface.
"""

from typing import Any, Optional

CONTRACT: str

def open(options: dict[str, Any]) -> Gmr: ...

class Gmr:
    def sample(self, anchor: str, how: Optional[dict[str, Any]] = None) -> dict[str, Any]: ...
    def read(self, anchor: str, how: Optional[dict[str, Any]] = None) -> dict[str, Any]: ...
    def ground(self, claims: list[str | dict[str, Any]], how: Optional[dict[str, Any]] = None) -> list[dict[str, Any]]: ...
    def since(self, cursor: int, status: Optional[str] = None) -> dict[str, Any]: ...
    def bind(self, claim: str, anchors: list[str], source: str, how: Optional[dict[str, Any]] = None) -> dict[str, Any]: ...
    def revoke(self, claim: str, source: str) -> dict[str, Any]: ...
    def link(self, from_: str, to: str, kind: str, source: str) -> None: ...
    def unlink(self, from_: str, to: str, kind: str, source: str) -> int: ...
    def anchors(self) -> list[dict[str, Any]]: ...
    def claims(self) -> list[Any]: ...
    def cobound(self, claim: str) -> list[Any]: ...
    def links(self, record: str) -> dict[str, Any]: ...
    def condense(self, said: str, into: str, source: str) -> dict[str, Any]: ...
    def open(self, request: dict[str, Any]) -> dict[str, Any]: ...
    def close(self, key: str, why: str) -> None: ...
